% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Methods 4 -- Portfolio 1},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Methods 4 -- Portfolio 1}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# update.packages(ask = FALSE, checkBuilt = TRUE)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \emph{Type:} Group assignment
\item
  \emph{Due:} 6 March 2022, 23:59
\end{itemize}

Okay here is a re-skinned version of some of McElreath's Exercises.

Have fun :)

Trigger alert for anyone who has recently experienced a pandemic.

\emph{-- Peter and Chris}

\hypertarget{pandemic-exercises}{%
\section{Pandemic Exercises}\label{pandemic-exercises}}

\hypertarget{testing-efficiency}{%
\subsection{1) Testing Efficiency}\label{testing-efficiency}}

Imagine there was a global pandemic.

It's a bit difficult, I know.

Maybe a new version of the old SARS-CoV turns out to be really
infectious, or something like that.

A test is developed that is cheap and quick to use, and the government
asks you to determine its efficiency.

To do this, they find X people that they know for sure are infected, and
X people that they know for sure are not infected. \emph{NB: This is not
always possible. For example, there is an ongoing global pandemic in the
real world - maybe you heard of it -where a 100\% sure test doesn't
exist, as far as I know. But let's ignore that. The government finds a
wizard who can tell for sure, but he wants a lot of money and he's
really slow too.}

Okay, so X infected people take the test, and X uninfected people take
the test. See the results below. P means positive, N means negative.

\begin{itemize}
\tightlist
\item
  Infected:
\end{itemize}

\[P, N, P, P, N, P, P, N, N, N, P, P, N, P, P, N, N, P, N, P\]

\begin{itemize}
\tightlist
\item
  Uninfected:
\end{itemize}

\[P, N, N, P, N, P, P, N, N, N, P, N, N, N, N, P, P, N, N, N\]

\textbf{A)} Estimate the probabilities of testing positive given that
you're infected, and given that you're not infected. Use the grid
approximation method as in the book. Use a prior you can defend using.
Report the full posterior probability distribution for each case (we can
do better than just a single value!).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Infected:}
\NormalTok{p\_grid }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\AttributeTok{from=}\DecValTok{0}\NormalTok{ , }\AttributeTok{to=}\DecValTok{1}\NormalTok{ , }\AttributeTok{length.out=}\DecValTok{1000}\NormalTok{ )}
\NormalTok{prior }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{ , }\DecValTok{1000}\NormalTok{ ) }\CommentTok{\# a flat prior as we assume it\textquotesingle{}s equally likely to be infected (it\textquotesingle{}s a very wicked virus)}
\NormalTok{likelihood }\OtherTok{\textless{}{-}} \FunctionTok{dbinom}\NormalTok{(}\DecValTok{11}\NormalTok{ , }\AttributeTok{size=}\DecValTok{20}\NormalTok{ , }\AttributeTok{prob=}\NormalTok{p\_grid) }\CommentTok{\# 11 out of 20}
\NormalTok{posterior }\OtherTok{\textless{}{-}}\NormalTok{ likelihood }\SpecialCharTok{*}\NormalTok{ prior}
\NormalTok{posterior }\OtherTok{\textless{}{-}}\NormalTok{ posterior }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(posterior)}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\NormalTok{samples\_infected }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(p\_grid , }\AttributeTok{prob=}\NormalTok{posterior , }\AttributeTok{size=}\FloatTok{1e4}\NormalTok{ , }\AttributeTok{replace=}\ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{dens}\NormalTok{(samples\_infected)}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Uninfected: }
\NormalTok{p\_grid }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\AttributeTok{from=}\DecValTok{0}\NormalTok{ , }\AttributeTok{to=}\DecValTok{1}\NormalTok{ , }\AttributeTok{length.out=}\DecValTok{1000}\NormalTok{ )}
\NormalTok{prior }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{ , }\DecValTok{1000}\NormalTok{ ) }\CommentTok{\# a flat prior as we assume it\textquotesingle{}s equally likely to be infected (it\textquotesingle{}s a very wicked virus)}
\NormalTok{likelihood }\OtherTok{\textless{}{-}} \FunctionTok{dbinom}\NormalTok{(}\DecValTok{7}\NormalTok{ , }\AttributeTok{size=}\DecValTok{20}\NormalTok{ , }\AttributeTok{prob=}\NormalTok{p\_grid) }\CommentTok{\# 7 out of 20}
\NormalTok{posterior }\OtherTok{\textless{}{-}}\NormalTok{ likelihood }\SpecialCharTok{*}\NormalTok{ prior}
\NormalTok{posterior }\OtherTok{\textless{}{-}}\NormalTok{ posterior }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(posterior)}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\NormalTok{samples\_uninfected }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(p\_grid , }\AttributeTok{prob=}\NormalTok{posterior , }\AttributeTok{size=}\FloatTok{1e4}\NormalTok{ , }\AttributeTok{replace=}\ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{dens}\NormalTok{(samples\_uninfected)}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-3-2.pdf}

\textbf{B)} The government says that they find probability distributions
difficult to use. They ask you to provide them with a confidence
interval of 95\% within which the `real' probability can be found. Do
it.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{HPDI}\NormalTok{(samples\_infected, }\AttributeTok{prob =} \FloatTok{0.95}\NormalTok{) }\CommentTok{\# 0.35 {-} 0.75}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     |0.95     0.95| 
## 0.3483483 0.7497497
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{HPDI}\NormalTok{(samples\_uninfected, }\AttributeTok{prob =} \FloatTok{0.95}\NormalTok{) }\CommentTok{\# 0.17 {-} 0.56}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     |0.95     0.95| 
## 0.1711712 0.5585586
\end{verbatim}

\textbf{C)} The government says that their voters find confidence
intervals difficult to read. In addition, they are so wide that it looks
like the government doesn't know what they're doing. They want a point
estimate instead. Give them one.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{chainmode}\NormalTok{(samples\_infected) }\CommentTok{\# 0.53}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.53483
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{chainmode}\NormalTok{(samples\_uninfected) }\CommentTok{\# 0.35}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.350261
\end{verbatim}

\textbf{Conclusion:} Summary of posterior predictive distributions:

\emph{For people infected:}

By examining the two posterior probability distributions, we get the
impression that there is a higher probability of testing positive if you
are actually infected than if you are not infected (luckily enough). The
confidence interval (HDPI interval) tells us that there is a 95\% chance
that the true probability of testing positive given that you are
infected is between 35\% and 75\%. This interval is pretty wide, so
therefor we also looked at the point estimate, which is the maximum
value of the posterior predictive distribution (the mode). Using the
point estimate, we can (carefully) conclude that there's around a 53\%
probability of being infected given a positive test.

\emph{For people NOT infected:}

For the people not infected, the HDPI interval tells us that there is a
95\% chance that the true probability of testing positive is between
17\% and 56\%. According to the point estimate, there is more precisely
a 35\% probability of testing positive given that you are not infected.
The point estimate is useful, because it is easy to interpret, but
nevertheless it is less informative than reporting a full
distribution.\\
We can indeed conclude that there is a higher probability of getting a
positive test result, given that you are actually infected.

\hypertarget{dark-cellars}{%
\subsection{2) Dark Cellars}\label{dark-cellars}}

Months pass. Thousands of people are tested by the wizards of the world
governments. A fancy company analyses the data, and determine, with very
high confidence they say, the probability of testing positive with the
current test. They give the following point estimates:

\begin{itemize}
\tightlist
\item
  A 53\% chance of testing positive if you are infected.
\item
  A 45\% chance of testing positive if you are not infected.
\end{itemize}

\emph{NB: These numbers also happen to be real estimates for the
efficiency of the COVID kviktest\footnote{I was lazy and just used this
  source:

  \url{https://www.ssi.dk/aktuelt/nyheder/2021/antigentest-gav-47-falsk-negative-svar}}.
Remember that the actual Danish government doesn't have any wizards,
though.}

\textbf{A)} You are sitting in your dark cellar room, trying to come up
with an apology to the Danish government, when you receive a positive
test result on your phone. Oh, that party last weekend. In order to
fight the boredom of isolation life, you start doing statistical
inference. Estimate the probability that you are infected, given that it
is \emph{a priori} equally likely to be infected or not to be.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Pr\_pos\_inf }\OtherTok{\textless{}{-}} \FloatTok{0.53} \CommentTok{\# probability of getting a positive test given you\textquotesingle{}re infected}
\NormalTok{Pr\_pos\_uninf }\OtherTok{\textless{}{-}} \FloatTok{0.45} \CommentTok{\# probability of getting a positive test given you\textquotesingle{}re NOT infected}
\NormalTok{Pr\_inf }\OtherTok{\textless{}{-}} \FloatTok{0.5} \CommentTok{\# general probability in population (prior)}

\NormalTok{Pr\_pos }\OtherTok{\textless{}{-}}\NormalTok{ Pr\_pos\_inf }\SpecialCharTok{*}\NormalTok{ Pr\_inf }\SpecialCharTok{+}\NormalTok{ Pr\_pos\_uninf }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ Pr\_inf) }\CommentTok{\# general prob of getting a positive result}

\CommentTok{\# the probability of being infected given a positive test (this is what we want)}
\NormalTok{Pr\_inf\_pos }\OtherTok{\textless{}{-}}\NormalTok{ Pr\_pos\_inf}\SpecialCharTok{*}\NormalTok{Pr\_inf }\SpecialCharTok{/}\NormalTok{ Pr\_pos }
\NormalTok{Pr\_inf\_pos }\CommentTok{\# 0.54}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5408163
\end{verbatim}

There's a 54\% probability of being infected given a positive test
result

\textbf{B)} A quick Google search tells you that about
546.000\footnote{\url{https://www.worldometers.info/coronavirus/\#countries}}
people in Denmark are infected right now. Use this for a prior instead.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Pr\_inf\_new }\OtherTok{\textless{}{-}} \DecValTok{546000}\SpecialCharTok{/}\FloatTok{5.8e6}
\NormalTok{Pr\_inf\_new }\CommentTok{\# 0.0941 (9\% of people are infected)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.09413793
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Pr\_pos }\OtherTok{\textless{}{-}}\NormalTok{ Pr\_pos\_inf }\SpecialCharTok{*}\NormalTok{ Pr\_inf\_new }\SpecialCharTok{+}\NormalTok{ Pr\_pos\_uninf }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ Pr\_inf\_new)}

\NormalTok{Pr\_inf\_pos }\OtherTok{\textless{}{-}}\NormalTok{ Pr\_pos\_inf}\SpecialCharTok{*}\NormalTok{Pr\_inf\_new }\SpecialCharTok{/}\NormalTok{ Pr\_pos}
\NormalTok{Pr\_inf\_pos}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1090486
\end{verbatim}

After updating our model, so that the prior is informed with the
\emph{actual} amount of infected people in the population: We see there
is only 11\% probability of actually being infected given that you get a
positive test result.

\textbf{C)} A friend calls and says that they have been determined by a
wizard to be infected. You and your friend danced tango together at the
party last weekend. It has been estimated that dancing tango with an
infected person leads to an infection 32\% of the time\footnote{That one
  I just made up.}. Incorporate this information in your estimate of
your probability of being infected.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Pr\_inf\_tango }\OtherTok{\textless{}{-}} \FloatTok{0.32}

\NormalTok{Pr\_pos }\OtherTok{\textless{}{-}}\NormalTok{ Pr\_pos\_inf }\SpecialCharTok{*}\NormalTok{ Pr\_inf\_tango }\SpecialCharTok{+}\NormalTok{ Pr\_pos\_uninf }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ Pr\_inf\_tango)}

\NormalTok{Pr\_inf\_pos\_tango }\OtherTok{\textless{}{-}}\NormalTok{ Pr\_pos\_inf}\SpecialCharTok{*}\NormalTok{Pr\_inf\_tango }\SpecialCharTok{/}\NormalTok{ Pr\_pos}
\NormalTok{Pr\_inf\_pos\_tango }\CommentTok{\# 0.3566}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3566022
\end{verbatim}

We assume that we disregard the information that only 9\% of the
population is actually infected. We then apply the 32\% prob of being
infected given tango dance as our new prior. This gives a 35.66\%
probability of being infected given a positive test and a tango dance.

\textbf{D)} You quickly run and get two more tests. One is negative, the
other positive. Update your estimate.

\begin{itemize}
\tightlist
\item
  A 53\% chance of testing positive if you are infected.
\item
  A 45\% chance of testing positive if you are not infected.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# taking our previous posterior making it a prior, but IN ODDS}
\NormalTok{Odds\_inf\_pos\_tango }\OtherTok{\textless{}{-}}\NormalTok{ Pr\_inf\_pos\_tango}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{Pr\_inf\_pos\_tango) }\CommentTok{\# turning the prior in probabilities into a prior in odds}

\CommentTok{\# Bayes factor given a positive test result}
\NormalTok{Bayes\_fact\_pos }\OtherTok{\textless{}{-}} \FloatTok{0.53}\SpecialCharTok{/}\FloatTok{0.45}

\CommentTok{\# Bayes factor given a negative test result}
\NormalTok{Bayes\_fact\_neg }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{1}\FloatTok{{-}0.53}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\FloatTok{{-}0.45}\NormalTok{)}

\CommentTok{\# now we can multiply the prior in odds with Bayes factor, first given a positive result and then multiply with bayes factor given a negative result}
\NormalTok{Updated\_odds }\OtherTok{\textless{}{-}}\NormalTok{ Odds\_inf\_pos\_tango}\SpecialCharTok{*}\NormalTok{Bayes\_fact\_pos}\SpecialCharTok{*}\NormalTok{Bayes\_fact\_neg }

\CommentTok{\# turning back into probabilities}
\NormalTok{Pr\_inf\_pos\_tango\_tests }\OtherTok{\textless{}{-}}\NormalTok{ Updated\_odds}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{+}\NormalTok{Updated\_odds)}
\NormalTok{Pr\_inf\_pos\_tango\_tests}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.358082
\end{verbatim}

Given another positive test result and another negative test result the
probability of being infected is now 35.80\%. This is slightly above
over estimate from before, but it seems as if the two tests cancel each
other.

\textbf{E)} In a questionnaire someone sent out for their exam project,
you have to answer if you think you are infected. You can only answer
yes or no (a bit like making a point estimate). What do you answer?

\textbf{Answer (E):}

In this calculation we've worked with the calculations in \emph{odds}.
By exploiting that updating can be done by multiplying a prior with
bayes factor. We assume that there's a 53\% chance of testing positive
if you are infected and a 45\% chance of testing positive if you are not
infected.

Assuming we've been dancing tango with an infected individual and have
gotten 1 positive and 1 negative test, we calculate that there's only
35.8\% probability of actually being infected. Therefore we say NO, we
don't not believe that we are infected.

\textbf{F)} You are invited to a party. They ask if you are infected.
They also say that they would prefer if you used an asymmetric loss
function when making your decision: it is three times worse to falsely
answer not infected, than to falsely answer infected. What do you
answer?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prob\_inf }\OtherTok{\textless{}{-}}\NormalTok{ Pr\_inf\_pos\_tango\_tests}
\NormalTok{prob\_uninf }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{{-}}\NormalTok{Pr\_inf\_pos\_tango\_tests}

\NormalTok{prob\_inf}\SpecialCharTok{*}\DecValTok{3} \CommentTok{\# cost of being infected}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.074246
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prob\_uninf}\SpecialCharTok{*}\DecValTok{1} \CommentTok{\# cost of not being infected}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.641918
\end{verbatim}

In part ``D'' we calculated the probability of being infected after
dancing tango and having the two test, this is
``Pr\_inf\_pos\_tango\_tests''. The probability of being infected is
deemeed 3 times as bad as not being infected, hence comparing the loss
in the two situations gives us a relative measure of cost.

As the cost associated with actually being infected after the two test
is larger than the cost of not being infected, we decide to stay at
home.

\hypertarget{causal-models}{%
\subsection{3) Causal Models}\label{causal-models}}

A problem from our textbook \emph{Statistical Rethinking (2nd ed.)}
(p.~160):

\begin{quote}
\textbf{5H4.} Here is an open practice problem to engage your
imagination. In the divorce data, states in the southern United States
have many of the highest divorce rates. Add the \texttt{South} indicator
variable to the analysis. First, draw one or more DAGs that represent
your ideas for how Southern American culture might influence any of the
other three variables (\(D\), \(M\), or \(A\)). Then list the testable
implications of your DAGs, if there are any, and fit one or more models
to evaluate the implications. What do you think the influence of
``Southernness'' is?
\end{quote}

5H4.1 - Drawing the DAGS

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# install.packages("dagitty")}
\FunctionTok{library}\NormalTok{(dagitty)}

\NormalTok{dag1 }\OtherTok{\textless{}{-}} \FunctionTok{dagitty}\NormalTok{( }\StringTok{"dag \{ M \textless{}{-} S {-}\textgreater{} A {-}\textgreater{} M {-}\textgreater{} D \textless{}{-} A\}"}\NormalTok{)}
\FunctionTok{coordinates}\NormalTok{(dag1) }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{( }\AttributeTok{x=}\FunctionTok{c}\NormalTok{(}\AttributeTok{D=}\DecValTok{0}\NormalTok{,}\AttributeTok{S=}\DecValTok{0}\NormalTok{, }\AttributeTok{M=}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\AttributeTok{A=}\DecValTok{1}\NormalTok{), }\AttributeTok{y=}\FunctionTok{c}\NormalTok{(}\AttributeTok{D=}\DecValTok{3}\NormalTok{, }\AttributeTok{M=}\DecValTok{2}\NormalTok{, }\AttributeTok{A=}\DecValTok{2}\NormalTok{, }\AttributeTok{S=}\DecValTok{1}\NormalTok{))}
\FunctionTok{drawdag}\NormalTok{( dag1 )}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-11-1.pdf}

Considerations behind our choice of DAG:

S -\textgreater{} A: We believe that Southerness directly influences age
of marriage due to several reasons. People from Southern states are
known to be more religious and conservative. We believe that their
prevalent positive view on the traditional marriage and their negative
views on e.g.~sex before marriage will cause people to marry younger. It
is simply a social norm. Another practical issue is that there in many
Southern states are more strict abortion rules, but as we all well know
that does not stop people from having sex. So it is possible to imagine
that if a woman gets pregnant, it is more likely that she will keep the
child than a woman from a Nothern State, and this might force the young
couple into marrying (again also because of social norms and concern for
reputation).

S -\textgreater{} M: We believe that Southerness directly influences
marriage rate because of the religious incentive to get married, as it
is the ``ideal'' life according to Christianity.

A -\textgreater{} D: We believe that age influences divorce rate
negatively, because of the assumption that the decision to marry was
less well thought through by young people than older people, meaning
that young people are more impulsive and driven by emotion, and therefor
more relationships break. Also, young people simply have longer time to
change and grow apart.

A -\textgreater{} M: We believe that age influences marriage rate
negatively, because if people marry from a younger age there are simply
more people to get married. So as the median age goes up, the marriage
rate goes down.

M -\textgreater{} D: We believe that marriage rate influences divorce
rate for the simple reason that more marriages increase the likelihood
of more divorces.

These are the links that we thought were reasonable to assume, but you
can of course make other DAGs. Some might argue that Southerness could
have a direct impact on divorce rate, so it is not merely mediated by
the links to age and marriage rate. Nevertheless, this is the DAG that
we went with.

\textbf{Testing Conditional Independencies:}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{impliedConditionalIndependencies}\NormalTok{(dag1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## D _||_ S | A, M
\end{verbatim}

In terms of correlations in the model, we see that D is independent from
S, conditional on A and M. Let's test this in our data:

Loading data:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(WaffleDivorce)}

\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{()}
\NormalTok{d}\SpecialCharTok{$}\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{standardize}\NormalTok{( WaffleDivorce}\SpecialCharTok{$}\NormalTok{MedianAgeMarriage )}
\NormalTok{d}\SpecialCharTok{$}\NormalTok{D }\OtherTok{\textless{}{-}} \FunctionTok{standardize}\NormalTok{( WaffleDivorce}\SpecialCharTok{$}\NormalTok{Divorce )}
\NormalTok{d}\SpecialCharTok{$}\NormalTok{M }\OtherTok{\textless{}{-}} \FunctionTok{standardize}\NormalTok{( WaffleDivorce}\SpecialCharTok{$}\NormalTok{Marriage )}
\NormalTok{d}\SpecialCharTok{$}\NormalTok{S }\OtherTok{\textless{}{-}} \FunctionTok{as.integer}\NormalTok{(WaffleDivorce}\SpecialCharTok{$}\NormalTok{South}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Testing Conditional Independencies:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mD\_SAM }\OtherTok{\textless{}{-}} \FunctionTok{quap}\NormalTok{(}
  \FunctionTok{alist}\NormalTok{(}
\NormalTok{   D }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(mu, sigma),}
\NormalTok{   mu }\OtherTok{\textless{}{-}}\NormalTok{ a[S] }\SpecialCharTok{+}\NormalTok{ b\_A}\SpecialCharTok{*}\NormalTok{A }\SpecialCharTok{+}\NormalTok{ b\_M}\SpecialCharTok{*}\NormalTok{M,}
\NormalTok{   a[S] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.2}\NormalTok{),}
\NormalTok{   b\_A }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.5}\NormalTok{),}
\NormalTok{   b\_M }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.5}\NormalTok{),}
\NormalTok{   sigma }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dexp}\NormalTok{(}\DecValTok{1}\NormalTok{)), }\AttributeTok{data =}\NormalTok{ d)}

\FunctionTok{precis\_plot}\NormalTok{(}\FunctionTok{precis}\NormalTok{(mD\_SAM, }\AttributeTok{depth=}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-14-1.pdf}

We wanted to see that S and D are independent (i.e.~the effect of S on D
is overlapping 0) when we stratify by A and M (i.e.~include them in our
model). This is exactly what we can see from the plot above.

\textbf{5H4.2 - Making models to test implications of our causal
reasoning:}

Making model:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# this model runs two regressions}
\NormalTok{m\_D\_A\_M\_S }\OtherTok{\textless{}{-}} \FunctionTok{quap}\NormalTok{(}
  \FunctionTok{alist}\NormalTok{(}
    \DocumentationTok{\#\# S {-}\textgreater{} A }
\NormalTok{    A }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(mu\_A, sigma\_A),}
\NormalTok{    mu\_A }\OtherTok{\textless{}{-}}\NormalTok{ aA[S],}
\NormalTok{    aA[S] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.2}\NormalTok{),}
\NormalTok{    sigma\_A }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dexp}\NormalTok{(}\DecValTok{1}\NormalTok{),}
    
    \DocumentationTok{\#\# A {-}\textgreater{} D \textless{}{-} M}
\NormalTok{    D }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{( mu , sigma ) ,}
\NormalTok{    mu }\OtherTok{\textless{}{-}}\NormalTok{ a }\SpecialCharTok{+}\NormalTok{ bM[S]}\SpecialCharTok{*}\NormalTok{M }\SpecialCharTok{+}\NormalTok{ bA[S]}\SpecialCharTok{*}\NormalTok{A ,}
\NormalTok{    a }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{( }\DecValTok{0}\NormalTok{ , }\FloatTok{0.2}\NormalTok{ ) ,}
\NormalTok{    bM[S] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{( }\DecValTok{0}\NormalTok{ , }\FloatTok{0.5}\NormalTok{ ) ,}
\NormalTok{    bA[S] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{( }\DecValTok{0}\NormalTok{ , }\FloatTok{0.5}\NormalTok{ ) ,}
\NormalTok{    sigma }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dexp}\NormalTok{( }\DecValTok{1}\NormalTok{ ),}
    
    \DocumentationTok{\#\# A {-}\textgreater{} M \textless{}{-} S}
\NormalTok{    M }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{( mu\_M , sigma\_M ),}
\NormalTok{    mu\_M }\OtherTok{\textless{}{-}}\NormalTok{ aM[S] }\SpecialCharTok{+}\NormalTok{ bAM[S]}\SpecialCharTok{*}\NormalTok{A,}
\NormalTok{    aM[S] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{( }\DecValTok{0}\NormalTok{ , }\FloatTok{0.2}\NormalTok{ ),}
\NormalTok{    bAM[S] }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dnorm}\NormalTok{( }\DecValTok{0}\NormalTok{ , }\FloatTok{0.5}\NormalTok{ ),}
\NormalTok{    sigma\_M }\SpecialCharTok{\textasciitilde{}} \FunctionTok{dexp}\NormalTok{( }\DecValTok{1}\NormalTok{ )}
\NormalTok{    ) , }\AttributeTok{data =}\NormalTok{ d )}

\FunctionTok{precis}\NormalTok{(m\_D\_A\_M\_S, }\AttributeTok{depth=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                mean         sd        5.5%      94.5%
## aA[1]    0.09338565 0.12514004 -0.10661231  0.2933836
## aA[2]   -0.14885848 0.15880166 -0.40265420  0.1049372
## sigma_A  0.95988800 0.09543649  0.80736206  1.1124139
## a       -0.04127333 0.09571905 -0.19425086  0.1117042
## bM[1]   -0.10531849 0.14866137 -0.34290807  0.1322711
## bM[2]    0.42396924 0.31818011 -0.08454403  0.9324825
## bA[1]   -0.53877157 0.15047099 -0.77925327 -0.2982899
## bA[2]   -0.83838169 0.31903953 -1.34826847 -0.3284949
## sigma    0.73027697 0.07369326  0.61250091  0.8480530
## aM[1]    0.04320631 0.09936658 -0.11560067  0.2020133
## aM[2]   -0.04535941 0.14730020 -0.28077358  0.1900548
## bAM[1]  -0.70253800 0.10196694 -0.86550085 -0.5395751
## bAM[2]  -0.54009160 0.27516963 -0.97986580 -0.1003174
## sigma_M  0.68019448 0.06807878  0.57139144  0.7889975
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# M and A are strongly negatively associated. If we interpret this causally, it indicates that manipulating A reduces M.}
\end{Highlighting}
\end{Shaded}

Now we have a bunch of parameters. In order to conclude on these, we are
going to simulate from them and do contrasting. By looking at the
parameters, we can get an idea about what could be interesting to dive
into. As a rule of thumb, if you can multiply the standard deviation
with two and add/subtract it from the mean, without the mean going to
zero, then you might have an interesting effect. As we see, this is in
most cases not possible with our model, but the two slopes for median
age do have this trade. Therefor, we will start by investigating our
claim that Southerness influences median marriage age.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  investigation: How does Southerness influence median-marriage-age?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# simulating}
\NormalTok{post }\OtherTok{\textless{}{-}} \FunctionTok{extract.samples}\NormalTok{(m\_D\_A\_M\_S)}

\FunctionTok{dens}\NormalTok{(post}\SpecialCharTok{$}\NormalTok{aA[,}\DecValTok{1}\NormalTok{], }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{, }\AttributeTok{col=}\DecValTok{4}\NormalTok{) }\CommentTok{\# blue = non{-}southern}
\FunctionTok{dens}\NormalTok{(post}\SpecialCharTok{$}\NormalTok{aA[,}\DecValTok{2}\NormalTok{], }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{, }\AttributeTok{col=}\DecValTok{2}\NormalTok{, }\AttributeTok{add=}\ConstantTok{TRUE}\NormalTok{) }\CommentTok{\# red = south}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-16-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{A1 }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\FloatTok{1e4}\NormalTok{, post}\SpecialCharTok{$}\NormalTok{aA[,}\DecValTok{1}\NormalTok{], post}\SpecialCharTok{$}\NormalTok{sigma\_A) }\CommentTok{\#simulating 10.000 observations and using the parameters from our model (for non{-}southerns)}
\NormalTok{A2 }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\FloatTok{1e4}\NormalTok{, post}\SpecialCharTok{$}\NormalTok{aA[,}\DecValTok{2}\NormalTok{], post}\SpecialCharTok{$}\NormalTok{sigma\_A) }\CommentTok{\#same for Southerns}
\FunctionTok{dens}\NormalTok{(A1, }\AttributeTok{col=}\DecValTok{4}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{) }\CommentTok{\# non{-}south = blue}
\FunctionTok{dens}\NormalTok{(A2, }\AttributeTok{col=}\DecValTok{2}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{, }\AttributeTok{add=}\ConstantTok{TRUE}\NormalTok{) }\CommentTok{\# south = red}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-16-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# contrast}
\NormalTok{A\_contrast }\OtherTok{\textless{}{-}}\NormalTok{ A2 }\SpecialCharTok{{-}}\NormalTok{ A1}
\FunctionTok{dens}\NormalTok{(A\_contrast,}
     \AttributeTok{col=}\DecValTok{3}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{3}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"posterior age contrast (year)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-16-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# proportion above zero}
\FunctionTok{sum}\NormalTok{(A\_contrast }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)}\SpecialCharTok{/}\FloatTok{1e4} \CommentTok{\# 42.64\%}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4345
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(A\_contrast }\SpecialCharTok{\textless{}} \DecValTok{0}\NormalTok{)}\SpecialCharTok{/}\FloatTok{1e4} \CommentTok{\# 57.36\%}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5655
\end{verbatim}

\textbf{Answer:} We see from the posterior predictive that there is a
lot of overlap, but in order to be able to conclude anything, it is
important to do the contrasting. From the contrast plot we see that the
distribution is centered pretty close around zero, but it is skewed a
little bit. More accurately, 57\% of times you randomly pick a
south-state, they have younger marriage age than non-south-state, based
on our simulations. This means that Southerness is \emph{not} a very
good predictor of median-age, as this is very close to chance level.

Next, we will investigate the other direct link from Southerness that we
assumed in our DAG.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  investigation: How does Southerners influence marriage rate?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m\_D\_A\_M\_S\_sim }\OtherTok{\textless{}{-}} \FunctionTok{sim}\NormalTok{(m\_D\_A\_M\_S,}
             \AttributeTok{n =} \FloatTok{1e4}\NormalTok{,}
             \AttributeTok{data =} \FunctionTok{list}\NormalTok{(}\AttributeTok{S=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{)),}
             \AttributeTok{vars=}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{,}\StringTok{"M"}\NormalTok{, }\StringTok{"D"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in if (left == var) {: the condition has length > 1 and only the first
## element will be used

## Warning in if (left == var) {: the condition has length > 1 and only the first
## element will be used

## Warning in if (left == var) {: the condition has length > 1 and only the first
## element will be used

## Warning in if (left == var) {: the condition has length > 1 and only the first
## element will be used
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M\_contrast }\OtherTok{\textless{}{-}}\NormalTok{ m\_D\_A\_M\_S\_sim}\SpecialCharTok{$}\NormalTok{M[,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{{-}}\NormalTok{m\_D\_A\_M\_S\_sim}\SpecialCharTok{$}\NormalTok{M[,}\DecValTok{1}\NormalTok{]}
\FunctionTok{dens}\NormalTok{(M\_contrast)}
\end{Highlighting}
\end{Shaded}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-17-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(M\_contrast }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)}\SpecialCharTok{/}\FloatTok{1e4} \CommentTok{\# 51.91\%}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5236
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(M\_contrast }\SpecialCharTok{\textless{}} \DecValTok{0}\NormalTok{)}\SpecialCharTok{/}\FloatTok{1e4} \CommentTok{\# 48.09\%}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4764
\end{verbatim}

\textbf{Answer:} Based on our contrasting, we estimate that 51.91\% of
the times you randomly pick a South state, their marriage rate will be
higher than that of a non-southern state. You literally cannot get much
closer to chance level, so we can conclude that Southerness is an
extremely poor predictor of marriage rate.

Since we in our DAG assume that there is no direct causal link between
Southerness and divorce rate, we should have encapsulated all the effect
from by investigating the effect from Southerness on age and marriage
rate. Since both of our analyses showed that Southerness was a very poor
predictor, we conclude that Southerness does not have a big impact on a
state's divorce rate.

\end{document}
